name = "AdaptiveFilters"
uuid = "c4f366c8-f60d-49ea-b3e5-386989159d04"
authors = ["Fredrik Bagge Carlson"]
version = "0.1.0"

[deps]
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
OnlineStats = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
